"""initial schema baseline

Revision ID: c0880aafa1bb
Revises: 
Create Date: 2026-07-30 08:46:56.039045
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c0880aafa1bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_sessions_expires_at'), 'anonymous_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_anonymous_sessions_status'), 'anonymous_sessions', ['status'], unique=False)
    op.create_table('custom_quote_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('pricing_unit', sa.String(length=20), nullable=False),
    sa.Column('material_grade', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_quote_rules_category'), 'custom_quote_rules', ['category'], unique=False)
    op.create_index(op.f('ix_custom_quote_rules_id'), 'custom_quote_rules', ['id'], unique=False)
    op.create_index(op.f('ix_custom_quote_rules_is_active'), 'custom_quote_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_custom_quote_rules_project_name'), 'custom_quote_rules', ['project_name'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('wechat', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('selling_point', sa.Text(), nullable=True),
    sa.Column('alternative', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_room'), 'products', ['room'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_style'), 'products', ['style'], unique=False)
    op.create_table('shop_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('wechat', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('slogan', sa.String(length=200), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('design_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('raw_user_input', sa.Text(), nullable=True),
    sa.Column('confirmed_requirement_json', sa.JSON(), nullable=True),
    sa.Column('space_type', sa.String(length=50), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # 历史数据库使用该索引名，下一版本统一索引名并补外键。
    op.create_index('idx_customer', 'design_tasks', ['customer_id'], unique=False)
    op.create_index(op.f('ix_design_tasks_id'), 'design_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_design_tasks_status'), 'design_tasks', ['status'], unique=False)
    op.create_table('anonymous_session_tasks',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['anonymous_sessions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['design_tasks.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'task_id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('chat_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['design_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_logs_id'), 'chat_logs', ['id'], unique=False)
    op.create_index(op.f('ix_chat_logs_task_id'), 'chat_logs', ['task_id'], unique=False)
    op.create_table('design_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('plans_json', sa.JSON(), nullable=True),
    sa.Column('quote_json', sa.JSON(), nullable=True),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.Column('generator', sa.String(length=20), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['design_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_results_id'), 'design_results', ['id'], unique=False)
    op.create_index(op.f('ix_design_results_task_id'), 'design_results', ['task_id'], unique=False)
    op.create_table('rendered_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.String(length=20), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['design_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rendered_images_id'), 'rendered_images', ['id'], unique=False)
    op.create_index(op.f('ix_rendered_images_plan_id'), 'rendered_images', ['plan_id'], unique=False)
    op.create_index(op.f('ix_rendered_images_task_id'), 'rendered_images', ['task_id'], unique=False)
    op.create_table('requirement_parse_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('follow_up_questions', sa.JSON(), nullable=True),
    sa.Column('parser', sa.String(length=20), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['design_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_parse_results_id'), 'requirement_parse_results', ['id'], unique=False)
    op.create_index(op.f('ix_requirement_parse_results_task_id'), 'requirement_parse_results', ['task_id'], unique=False)
    op.create_table('uploaded_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['design_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_images_id'), 'uploaded_images', ['id'], unique=False)
    op.create_table('anonymous_session_images',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['uploaded_images.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['anonymous_sessions.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'image_id'),
    sa.UniqueConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anonymous_session_images')
    op.drop_index(op.f('ix_uploaded_images_id'), table_name='uploaded_images')
    op.drop_table('uploaded_images')
    op.drop_index(op.f('ix_requirement_parse_results_task_id'), table_name='requirement_parse_results')
    op.drop_index(op.f('ix_requirement_parse_results_id'), table_name='requirement_parse_results')
    op.drop_table('requirement_parse_results')
    op.drop_index(op.f('ix_rendered_images_task_id'), table_name='rendered_images')
    op.drop_index(op.f('ix_rendered_images_plan_id'), table_name='rendered_images')
    op.drop_index(op.f('ix_rendered_images_id'), table_name='rendered_images')
    op.drop_table('rendered_images')
    op.drop_index(op.f('ix_design_results_task_id'), table_name='design_results')
    op.drop_index(op.f('ix_design_results_id'), table_name='design_results')
    op.drop_table('design_results')
    op.drop_index(op.f('ix_chat_logs_task_id'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_id'), table_name='chat_logs')
    op.drop_table('chat_logs')
    op.drop_table('anonymous_session_tasks')
    op.drop_index(op.f('ix_design_tasks_status'), table_name='design_tasks')
    op.drop_index(op.f('ix_design_tasks_id'), table_name='design_tasks')
    op.drop_index('idx_customer', table_name='design_tasks')
    op.drop_table('design_tasks')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('shop_settings')
    op.drop_index(op.f('ix_products_style'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_room'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_custom_quote_rules_project_name'), table_name='custom_quote_rules')
    op.drop_index(op.f('ix_custom_quote_rules_is_active'), table_name='custom_quote_rules')
    op.drop_index(op.f('ix_custom_quote_rules_id'), table_name='custom_quote_rules')
    op.drop_index(op.f('ix_custom_quote_rules_category'), table_name='custom_quote_rules')
    op.drop_table('custom_quote_rules')
    op.drop_index(op.f('ix_anonymous_sessions_status'), table_name='anonymous_sessions')
    op.drop_index(op.f('ix_anonymous_sessions_expires_at'), table_name='anonymous_sessions')
    op.drop_table('anonymous_sessions')
    # ### end Alembic commands ###
